from enum import Enum


class ConversationState(str, Enum):
    IDLE = "IDLE"
    COLLECTING_ORDER = "COLLECTING_ORDER"
    ASKING_CUSTOMER_NAME = "ASKING_CUSTOMER_NAME"
    ASKING_DELIVERY_TYPE = "ASKING_DELIVERY_TYPE"
    ASKING_ADDRESS = "ASKING_ADDRESS"
    ASKING_LOCATION = "ASKING_LOCATION"
    CONFIRMING_ORDER = "CONFIRMING_ORDER"
    ORDER_COMPLETED = "ORDER_COMPLETED"


class OrderStatus(str, Enum):
    PENDING = "PENDING"
    CONFIRMED = "CONFIRMED"
    PREPARING = "PREPARING"
    DELIVERING = "DELIVERING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
